### ISSUE TITLE
datasets 

### ISSUE THREAD

**Issue by cv-lab-x** [XchaoWu/Scalable-Neural-Indoor-Scene-Rendering#1]
hi, thanks for your great work! could you give the datasets link in your paper to reproduce the work? @XchaoWu 
Looking forward to your reply, thanks!

**Comment by XchaoWu** [comment]
Hi, I am sorry that I can only share one dataset at the moment, (busy with another project 😭). 
Living room -> https://drive.google.com/file/d/1ZMsYnB_cVxzUKrQ2oxXifPSvcTs5LpeZ/view?usp=sharing

**Comment by shengzhesz** [comment]
> Hi, I am sorry that I can only share one dataset at the moment, (busy with another project sob). Living room -> https://drive.google.com/file/d/1ZMsYnB_cVxzUKrQ2oxXifPSvcTs5LpeZ/view?usp=sharing

Thanks for the data. I still have some questions.
1. When training the tiles, depth images are needed. Should I render the depth data from the given mesh? 
2. If I want to do the training on our own data, how to generate the "/livingroom/tiles/ *.npy" files? Could you share the preprocessing scripts?
