### ISSUE TITLE
Low rendering frame rate at 3090

### ISSUE THREAD

**Issue by 1742483876** [XchaoWu/Scalable-Neural-Indoor-Scene-Rendering#3]
Thank you for your great work.However, When we tried to render the demo on a 3090 graphics card, the rendering frame rate was only 0.5fps. Have you ever encountered this problem and how can I fix it?

**Comment by XchaoWu** [comment]
Hi, could you just test the rendering frame rate of diffuse color and reflections separately?  If the low FPS is caused by the reflections rendering, then it may be because the register is bounded when compiling the fully fused MLP.  You can add `-Xptxas -v` options to NVCC to check the problem~
And my ptxas info of function `inference_mlp_kernel` is:
```
ptxas info    : 15 bytes gmem, 12 bytes cmem[3]
ptxas info    : Compiling entry function '_ZN3cub11EmptyKernelIvEEvv' for 'sm_86'
ptxas info    : Function properties for _ZN3cub11EmptyKernelIvEEvv
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 4 registers, 352 bytes cmem[0]
ptxas info    : Compiling entry function '_Z20inference_mlp_kernelifPsPffPKiS2_PKfS4_PK6float3PK6__halfP6float4' for 'sm_86'
ptxas info    : Function properties for _Z20inference_mlp_kernelifPsPffPKiS2_PKfS4_PK6float3PK6__halfP6float4
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 88 registers, 45124 bytes smem, 440 bytes cmem[0]
```

**Comment by YJJfish** [comment]
I have the same problem. The rendering frame rate for "Reflection" mode is only 0.5fps, but for "Diffuse" mode it is 60fps or more. So how to fix this problem?

**Comment by XchaoWu** [comment]
> I have the same problem. The rendering frame rate for "Reflection" mode is only 0.5fps, but for "Diffuse" mode it is 60fps or more. So how to fix this problem?

 Check if your NVCC version is 11.1, and then follow what I mentioned in last answer, checking the number of registers used in function `inference_mlp_kernel`.  I guess it is because this function uses more register resources in your GPU.

**Comment by 1742483876** [comment]
> > I have the same problem. The rendering frame rate for "Reflection" mode is only 0.5fps, but for "Diffuse" mode it is 60fps or more. So how to fix this problem?
> 
> Check if your NVCC version is 11.1, and then follow what I mentioned in last answer, checking the number of registers used in function `inference_mlp_kernel`. I guess it is because this function uses more register resources in your GPU.

Thanks for your answer, I solved the problem by changing the cuda version to 11.1
