### ISSUE TITLE
Questions about the the input data.

### ISSUE THREAD

**Issue by shengzhesz** [XchaoWu/Scalable-Neural-Indoor-Scene-Rendering#4]
Hi, I am sorry that I can only share one dataset at the moment, (busy with another project 😭). 
Living room -> https://drive.google.com/file/d/1ZMsYnB_cVxzUKrQ2oxXifPSvcTs5LpeZ/view?usp=sharing

_Originally posted by @XchaoWu in https://github.com/XchaoWu/Scalable-Neural-Indoor-Scene-Rendering/issues/1#issuecomment-1316199241_

Thanks for the data. I still have some questions.
1. When training the tiles, depth images are needed. Should I render the depth data from the given mesh?
2. If I want to do the training on our own data, how to generate the "/livingroom/tiles/ *.npy" files? Could you share the preprocessing scripts?

**Comment by XchaoWu** [comment]
> ```
>     Hi, I am sorry that I can only share one dataset at the moment, (busy with another project 😭). 
> ```
> 
> Living room -> https://drive.google.com/file/d/1ZMsYnB_cVxzUKrQ2oxXifPSvcTs5LpeZ/view?usp=sharing
> 
> _Originally posted by @XchaoWu in [#1 (comment)](https://github.com/XchaoWu/Scalable-Neural-Indoor-Scene-Rendering/issues/1#issuecomment-1316199241)_
> 
> Thanks for the data. I still have some questions.
> 
> 1. When training the tiles, depth images are needed. Should I render the depth data from the given mesh?
> 2. If I want to do the training on our own data, how to generate the "/livingroom/tiles/ *.npy" files? Could you share the preprocessing scripts?

1. We didn't use the depth map in the process of training. You can locate line  1341 of function `get_trainData_v3` and comment out the code that lodes the depth images. 
2. Currently the code about preprocessing is not well organized, I will publish this part as soon as possible. Or if you really need this code, I can send you the unorganized code by email.

**Comment by shengzhesz** [comment]
Thank you for pointing out what should be commented out.
If it is convenient, please send me the

**Comment by shengzhesz** [comment]
Thank you for pointing out what should be commented out.
If it is convenient, please send me the unorganized preprocessing code by email: shengzhesz@gmail.com. Thank you very much!

**Comment by XchaoWu** [comment]
> 

Hi, I already send the code to you.

**Comment by shengzhesz** [comment]
Got it, thanks so much！

Wu Xiuchao ***@***.***> 于2022年12月6日周二 14:54写道：

**Comment by tommaoer** [comment]
> 
@XchaoWu 
Hi, could you share the code with me. I also want to training the own data. Thanks
If it is convenient, Please send me the preprocessing code. email: yj444757397@gmail.com.
Thanks a lot.
